
version: '3.4'



services:

  iotapi:

    image: IoTProject301

    build:

      context: .

      dockerfile: ./Dockerfile

    ports:

      - 5000:5000

    environment:

      - ASPNETCORE_ENVIRONMENT=Development

    volumes:

      - ~/.vsdbg:c:\remote_debugger:rw